UI Improvements
intermine/bluegenes-tissue-expression-visualizer pull request #11
Opened 2020-03-16 20:20 UTC by jsnunki

This PR has multiple improvements:
- The graphics now has a 100% width with a min-width of 700px (small screens) and a max-width of 1200px (Desktop screens).
- The graphics container has been centered.
- The controls are full clickable that means you can click the square instead of having to click the specific checkbox.

Note: The min-width of 700px was added because below that is not possible to avoid the overlap labels, this is an issue with the chart.js library itself.

![image](https://user-images.githubusercontent.com/5965987/76796540-f5517600-67cb-11ea-9d98-43468e903423.png)
![image](https://user-images.githubusercontent.com/5965987/76796527-eb2f7780-67cb-11ea-9a9d-64a45a83eead.png)

2020-03-20 11:19 UTC, heralden requested changes
Please check my comment before I test this further. [=

2020-03-20 11:19 UTC, uosl commented on src/style.less
> +.main-container {
Would it work to have these styles apply to `.rootContainer` instead? The containing div element won't have the `.main-container` class when used in Bluegenes.

2020-03-20 15:10 UTC, jsnunki commented
@uosl Ready to update .rootContainer with .main-container styles. and works

In this PR you also have the changes after changing url from https to http trying to solve: [FAIL tests / tissueExpression.test.js: Cannot find module 'es6-promise' from 'promise.js' # 10](https://github.com/intermine/bluegenes-tissue-expression-visualizer/issues/10)

2020-03-23 14:19 UTC, heralden approved these changes
Thank you, this works great. :100:

2020-03-23 14:20 UTC, merged